version: '2'
services:
  mongo:
    image: mongo:3.6
    ports: ["27017:27017"]
    volumes:
      - ./db:/data/db
  mtss:
    build: .      
    restart: always
    depends_on:
      - mongo
    ports: ["8000:8000"]
    env_file:
      - .env